global:
  scrape_interval: 5s
  evaluation_interval: 5s
  # Attach these labels to any time series or alerts when communicating with external systems
  external_labels:
    monitor: 'fastapi-metrics-monitor'

# Rules configuration
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# Alerting configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Scrape configuration
scrape_configs:
  # FastAPI application metrics
  - job_name: 'fastapi'
    static_configs:
      - targets: ['fastapi-app:8000']
    metrics_path: '/metrics'
    scrape_interval: 5s
    scrape_timeout: 4s
    honor_labels: true
    honor_timestamps: true
    
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 15s
    
  # Optional: Add Grafana metrics if needed
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s